const dependencies = {
  '@hot-loader/react-dom': '16.8.6',
  dotenv: '^6.2.0',
  'eslint-config-airbnb': '^17.1.0',
  'eslint-config-prettier': '^4.1.0',
  'eslint-plugin-prettier': '^3.0.1',
  prettier: '^1.16.4',
  'prop-types': '15.6.2',
  react: '16.8.6',
  'react-dev-utils': '^6.0.4',
  'react-dom': '16.8.6',
  'react-hot-loader': '^4.8.3',
  'react-redux': '5.1.1',
  'react-router-dom': '4.3.1',
  redux: '4.0.1',
  'redux-thunk': '2.3.0',
};

const devDependencies = {
  '@babel/cli': '^7.2.3',
  '@babel/core': '^7.0.0-0',
  '@babel/plugin-proposal-class-properties': '^7.4.0',
  '@babel/plugin-syntax-dynamic-import': '^7.2.0',
  '@babel/plugin-transform-runtime': '^7.4.3',
  '@babel/preset-env': '^7.4.2',
  '@babel/preset-react': '^7.0.0',
  'babel-core': '7.0.0-bridge.0',
  'babel-eslint': '9.0.0',
  'babel-jest': '^23.6.0',
  'babel-loader': '^8.0.4',
  eslint: '5.6.0',
  'eslint-plugin-import': '2.14.0',
  'eslint-plugin-jsx-a11y': '6.1.1',
  'eslint-plugin-react': '^7.12.4',
  'eslint-plugin-react-hooks': '^1.5.0',
  husky: '^1.2.0',
  jest: '^24.1.0',
  'parcel-bundler': '^1.12.3',
  stylelint: '^9.10.1',
  'stylelint-config-css-modules': '^1.3.0',
  'stylelint-config-prettier': '^5.0.0',
  'stylelint-config-recommended': '^2.1.0',
  'stylelint-config-sass-guidelines': '^5.3.0',
  'stylelint-config-standard': '^18.2.0',
  'stylelint-prettier': '^1.0.6',
  'stylelint-config-rational-order': '^0.1.0',
};

module.exports = {
  dependencies,
  devDependencies,
};
